ARG BASE_REGISTRY=public.ecr.aws
FROM ${BASE_REGISTRY}/docker/library/alpine:3

ARG CURL_VERSION

RUN apk update && \
    apk add \
        openjdk11 \
        file \
        g++ \
        gcc \
        make \
        patch \
        perl

# Install curl dependency
COPY ./deps/curl-$CURL_VERSION.tar.gz /src/deps/
COPY ./deps/curl_001_disable_wakeup.patch /src/deps/

RUN tar xzf /src/deps/curl-$CURL_VERSION.tar.gz -C /src/deps

WORKDIR /src/deps/curl-$CURL_VERSION
RUN patch lib/multihandle.h ../curl_001_disable_wakeup.patch
RUN ./configure \
        --prefix $(pwd)/../artifacts \
        --disable-shared \
        --without-ssl \
        --with-pic \
        --without-zlib && \
    make && \
    make install

COPY ./deps/aws-lambda-cpp/include /src/deps/artifacts/include
COPY ./deps/aws-lambda-cpp/lib/libaws-lambda-runtime.a /src/deps/artifacts/lib/

# Build native client
ADD *.cpp *.h /src/
WORKDIR /src

ENV JAVA_HOME=/usr/lib/jvm/java-11-openjdk
RUN /usr/bin/c++ -c \
        -std=gnu++11 \
        -fPIC \
        -I${JAVA_HOME}/include \
        -I${JAVA_HOME}/include/linux \
        -I ./deps/artifacts/include \
        com_amazonaws_services_lambda_runtime_api_client_runtimeapi_NativeClient.cpp -o com_amazonaws_services_lambda_runtime_api_client_runtimeapi_NativeClient.o && \
    /usr/bin/c++ -c \
        -std=gnu++11 \
        -fPIC \
        -I${JAVA_HOME}/include \
        -I${JAVA_HOME}/include/linux \
        -I ./deps/artifacts/include \
        com_amazonaws_services_lambda_crac_DNSManager.cpp -o com_amazonaws_services_lambda_crac_DNSManager.o && \
    /usr/bin/c++ -shared \
        -std=gnu++11 \
        -o aws-lambda-runtime-interface-client.so com_amazonaws_services_lambda_runtime_api_client_runtimeapi_NativeClient.o com_amazonaws_services_lambda_crac_DNSManager.o \
        -L ./deps/artifacts/lib/ \
        -laws-lambda-runtime \
        -lcurl \
        -static-libstdc++ \
        -static-libgcc \
        -O2
