# This workflow will be triggered if there will be changes to aws-lambda-java-serialization 
# package and it builds the package and the packages that depend on it.

name: Java CI aws-lambda-java-serialization

on:
  push:
    branches: [ master ]
    paths:
    - 'aws-lambda-java-serialization/**'
  pull_request:
    branches: [ '*' ]
    paths:
    - 'aws-lambda-java-serialization/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # Install base module
    - name: Install events with Maven
      run: mvn -B install --file aws-lambda-java-events/pom.xml
    # Package target module
    - name: Package serialization with Maven
      run: mvn -B package --file aws-lambda-java-serialization/pom.xml
