# This workflow will be triggered if there will be changes to 
# aws-lambda-java-events-sdk-transformer package and it builds the package.

name: Java CI aws-lambda-java-events-sdk-transformer

on:
  push:
    branches: [ main ]
    paths:
      - 'aws-lambda-java-events-sdk-transformer/**'
  pull_request:
    branches: [ '*' ]
    paths:
      - 'aws-lambda-java-events-sdk-transformer/**'
      - '.github/workflows/aws-lambda-java-events-sdk-transformer.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: corretto

    # Install base module
    - name: Install events with Maven
      run: mvn -B install --file aws-lambda-java-events/pom.xml
    # Package target module
    - name: Package events-sdk-transformer with Maven
      run: mvn -B package --file aws-lambda-java-events-sdk-transformer/pom.xml
    
