# This workflow will be triggered if there will be changes to 
# aws-lambda-java-events-sdk-transformer package and it builds the package.

name: Java CI aws-lambda-java-events-sdk-transformer

on:
  push:
    branches: [ master ]
    paths:
    - 'aws-lambda-java-events-sdk-transformer/**'
  pull_request:
    branches: [ '*' ]
    paths:
    - 'aws-lambda-java-events-sdk-transformer/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # Install base module
    - name: Build events-sdk-transformer with Maven
      run: mvn -B install --file aws-lambda-java-events-sdk-transformer/pom.xml
    
