# This workflow will be triggered if there will be changes to aws-lambda-java-core
# package and it builds the package and the packages that depend on it.

name: Java CI aws-lambda-java-core

on:
  push:
    branches: [ master ]
    paths:
    - 'aws-lambda-java-core/**'
  pull_request:
    branches: [ '*' ]
    paths:
    - 'aws-lambda-java-core/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # Install base module
    - name: Install core with Maven
      run: mvn -B install --file aws-lambda-java-core/pom.xml

    # Package modules that depend on base module
    - name: Package log4j2 with Maven
      run: mvn -B package --file aws-lambda-java-log4j2/pom.xml

    # Test Runtime Interface Client
    - name: Run 'pr' target
      working-directory: ./aws-lambda-java-runtime-interface-client
      run: make pr
