# This workflow will be triggered if there will be changes to aws-lambda-java-serialization 
# package and it builds the package and the packages that depend on it.

name: Java CI aws-lambda-java-serialization

on:
  push:
    branches: [ main ]
    paths:
    - 'aws-lambda-java-serialization/**'
  pull_request:
    branches: [ '*' ]
    paths:
    - 'aws-lambda-java-serialization/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8
        distribution: corretto
    
    # Install base module
    - name: Install events with Maven
      run: mvn -B install --file aws-lambda-java-events/pom.xml

    # Package and install target module
    - name: Package serialization with Maven
      run: mvn -B package install --file aws-lambda-java-serialization/pom.xml

    # Run tests
    - name: Run tests from aws-lambda-java-tests
      run: mvn test --file aws-lambda-java-tests/pom.xml
