# This workflow will be triggered if there will be changes to 
# aws-lambda-java-log4j2 package and it builds the package.

name: Java CI aws-lambda-java-log4j2

on:
  push:
    branches: [ master ]
    paths:
    - 'aws-lambda-java-log4j2/**'
  pull_request:
    branches: [ '*' ]
    paths:
    - 'aws-lambda-java-log4j2/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # Install base module
    - name: Install core with Maven
      run: mvn -B install --file aws-lambda-java-core/pom.xml
    # Package target module
    - name: Package log4j2 with Maven
      run: mvn -B package --file aws-lambda-java-log4j2/pom.xml
    
