# This workflow will build all Java packages in this project with Maven (Java 8)

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    # Install base modules
    - name: Build core with Maven
      run: mvn -B install --file aws-lambda-java-core/pom.xml
    - name: Build events with Maven
      run: mvn -B install --file aws-lambda-java-events/pom.xml

    # Package modules that depend on base modules
    - name: Build events-sdk-transformer with Maven
      run: mvn -B package --file aws-lambda-java-events-sdk-transformer/pom.xml
    - name: Build log4j2 with Maven
      run: mvn -B package --file aws-lambda-java-log4j2/pom.xml
