# This workflow will be triggered on merge to the main branch if
# aws-lambda-java-runtime-interface-client package was changed
#
# It will build and test the aws-lambda-java-runtime-interface-client and publish CODECOV report

name: Build, test and publish coverage for aws-lambda-java-runtime-interface-client

on:
  push:
    branches: [ main ]
    paths:
    - 'aws-lambda-java-runtime-interface-client/**'
    - '.github/workflows/runtime-interface-client_merge_to_main.yml'
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        java-version: 8
        distribution: corretto

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true

    - name: Available buildx platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
          
    - name: Test Runtime Interface Client xplatform build - Run 'build' target
      working-directory: ./aws-lambda-java-runtime-interface-client
      run: make build
      env:
        IS_JAVA_8: true

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
